version: '3'
services:
  db:
    image: rethinkdb:2.3.5
    ports:
      - 4005:8080

  movie-service:
    build: .
    working_dir: /usr/app
    depends_on:
      - db
    ports:
      - 4000
    environment:
      - DB_HOST=db